### ISSUE TITLE
Break CI chunks into action steps

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/action-ignition-ci#3]
GitHub action jobs can be run in several [steps](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps) which can be collapsed when looking at the results, so it would be nice if this action could also be broken into various steps.

However, I couldn't find a good way to separate steps for a docker action like this one. So:

* Either there's something that can be called from within the docker file to start a new step but I haven't found
* Or there may be a nice way to create docker files that can be run in a chain (?)
* Or we could refactor this action to use something other than docker

**Comment by scpeters** [comment]
it looks like dart is able to use a docker container across multiple steps with a `docker build`, then `docker run -itd`  which detaches the container and keeps it running, and uses subsequent calls to `docker exec` for the additional steps

**Comment by scpeters** [comment]
sorry, meant to include a link: https://github.com/dartsim/dart/blob/master/.github/workflows/ccpp.yml#L20-L33

**Comment by chapulina** [comment]
Nice! I see they're not using the Docker actions (`using: 'docker'`), but that's fine. I can look into this later this week.
